<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="6" hostname="StationOne-PC" failures="2" tests="8" name="TC_01_Epam" time="18.246" errors="0" timestamp="17 Jan 2020 10:46:04 GMT">
  <testcase classname="com.demo.test_suites.backend.TS_01_Login" name="accessToken" time="1.418"/>
  <testcase classname="com.demo.test_suites.backend.TS_01_Login" name="newUser" time="0.387">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at com.demo.test_scripts.api.RegisterUser.getNewUser(RegisterUser.java:87)
at com.demo.test_suites.backend.TS_01_Login.newUser(TS_01_Login.java:28)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
    </failure>
  </testcase> <!-- newUser -->
  <testcase classname="com.demo.test_suites.backend.TS_01_Login" name="login" time="0.485"/>
  <testcase classname="com.demo.test_suites.backend.TS_01_Login" name="addAccountInfo" time="0.385">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at com.demo.test_scripts.api.NewToken.addUserInfo(NewToken.java:89)
at com.demo.test_suites.backend.TS_01_Login.addAccountInfo(TS_01_Login.java:42)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
    </failure>
  </testcase> <!-- addAccountInfo -->
  <testcase classname="com.demo.test_suites.backend.TS_01_Login" name="userInfo" time="0.369"/>
  <testcase classname="com.demo.test_suites.frontend.TS_01_Items" name="loadHomePage" time="2.616"/>
  <testcase classname="com.demo.test_suites.frontend.TS_01_Items" name="searchItem" time="5.094"/>
  <testcase classname="com.demo.test_suites.frontend.TS_01_Items" name="openItemDescription" time="7.446"/>
  <testcase classname="com.demo.config.BasicConfiguration" name="@BeforeSuite browserConfig" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite browserConfig -->
  <testcase classname="com.demo.config.BasicConfiguration" name="@AfterSuite flushReportData" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite flushReportData -->
  <testcase classname="com.demo.config.BasicConfiguration" name="@BeforeSuite cleanReportData" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite cleanReportData -->
  <testcase classname="com.demo.config.BasicConfiguration" name="@AfterSuite tearDown" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite tearDown -->
  <testcase classname="com.demo.config.BasicConfiguration" name="@BeforeSuite setEnvironmentConfiguration" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite setEnvironmentConfiguration -->
  <testcase classname="com.demo.config.BasicConfiguration" name="@AfterSuite clearXmlFiles" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite clearXmlFiles -->
</testsuite> <!-- TC_01_Epam -->
