<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="QAIT006" name="com.demo.tests.TestCase_03_Leveraged" tests="7" failures="0" timestamp="01 Apr 2020 15:34:24 GMT" time="8.990" errors="1">
  <testcase name="post_login" time="0.642" classname="com.demo.tests.TestCase_03_Leveraged"/>
  <testcase name="get_user_info" time="0.251" classname="com.demo.tests.TestCase_03_Leveraged"/>
  <testcase name="get_product_list" time="0.857" classname="com.demo.tests.TestCase_03_Leveraged"/>
  <testcase name="web_login" time="1.401" classname="com.demo.tests.TestCase_03_Leveraged"/>
  <testcase name="web_leveraged_filters" time="3.616" classname="com.demo.tests.TestCase_03_Leveraged">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.demo.scripts.ui.filters.LaveragesFilters.leveragesFilters(LaveragesFilters.java:70)
at com.demo.tests.TestCase_03_Leveraged.web_leveraged_filters(TestCase_03_Leveraged.java:55)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.TestNG.privateMain(TestNG.java:1354)
at org.testng.TestNG.main(TestNG.java:1323)
]]>
    </error>
  </testcase> <!-- web_leveraged_filters -->
  <testcase name="web_search_for_product" time="1.143" classname="com.demo.tests.TestCase_03_Leveraged"/>
  <testcase name="web_open_leveraged_product" time="1.080" classname="com.demo.tests.TestCase_03_Leveraged"/>
</testsuite> <!-- com.demo.tests.TestCase_03_Leveraged -->
